### ISSUE TITLE
Change on the innit code hash for the Elk Library

### ISSUE THREAD

**Issue by otherview** [elkfinance/exchange-contracts#2]
https://github.com/elkfinance/exchange-contracts/commit/6fde70aa231662b61dcdbe76766cba6bc7da5097#r64254450

Is that new value correct ? I can't seem to generate the mainnet pairs with the new one, only with the old one.

**Comment by baal314** [comment]
The code hash depends on the chain. Which one do you need?

**Comment by otherview** [comment]
Gotcha 👍  

Working with avalanche, the previous hash works fine.  
Probably would be nice to have a comment in that file with the hashes/chains.

Thanks for the quick reply, closing the issue.
